// Code generated by entc, DO NOT EDIT.

package systemmember

const (
	// Label holds the string label denoting the systemmember type in the database.
	Label = "systemmember"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMail holds the string denoting the mail field in the database.
	FieldMail = "mail"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"

	// EdgePersonal holds the string denoting the personal edge name in mutations.
	EdgePersonal = "personal"

	// Table holds the table name of the systemmember in the database.
	Table = "systemmembers"
	// PersonalTable is the table the holds the personal relation/edge.
	PersonalTable = "personals"
	// PersonalInverseTable is the table name for the Personal entity.
	// It exists in this package in order to avoid circular dependency with the "personal" package.
	PersonalInverseTable = "personals"
	// PersonalColumn is the table column denoting the personal relation/edge.
	PersonalColumn = "systemmember_id"
)

// Columns holds all SQL columns for systemmember fields.
var Columns = []string{
	FieldID,
	FieldMail,
	FieldPassword,
}
