// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/ssaatw/app/ent/jobtitle"
)

// Jobtitle is the model entity for the Jobtitle schema.
type Jobtitle struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Jobtitlename holds the value of the "Jobtitlename" field.
	Jobtitlename string `json:"Jobtitlename,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the JobtitleQuery when eager-loading is set.
	Edges JobtitleEdges `json:"edges"`
}

// JobtitleEdges holds the relations/edges for other nodes in the graph.
type JobtitleEdges struct {
	// Personal holds the value of the personal edge.
	Personal []*Personal
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PersonalOrErr returns the Personal value or an error if the edge
// was not loaded in eager-loading.
func (e JobtitleEdges) PersonalOrErr() ([]*Personal, error) {
	if e.loadedTypes[0] {
		return e.Personal, nil
	}
	return nil, &NotLoadedError{edge: "personal"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Jobtitle) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // Jobtitlename
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Jobtitle fields.
func (j *Jobtitle) assignValues(values ...interface{}) error {
	if m, n := len(values), len(jobtitle.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	j.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field Jobtitlename", values[0])
	} else if value.Valid {
		j.Jobtitlename = value.String
	}
	return nil
}

// QueryPersonal queries the personal edge of the Jobtitle.
func (j *Jobtitle) QueryPersonal() *PersonalQuery {
	return (&JobtitleClient{config: j.config}).QueryPersonal(j)
}

// Update returns a builder for updating this Jobtitle.
// Note that, you need to call Jobtitle.Unwrap() before calling this method, if this Jobtitle
// was returned from a transaction, and the transaction was committed or rolled back.
func (j *Jobtitle) Update() *JobtitleUpdateOne {
	return (&JobtitleClient{config: j.config}).UpdateOne(j)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (j *Jobtitle) Unwrap() *Jobtitle {
	tx, ok := j.config.driver.(*txDriver)
	if !ok {
		panic("ent: Jobtitle is not a transactional entity")
	}
	j.config.driver = tx.drv
	return j
}

// String implements the fmt.Stringer.
func (j *Jobtitle) String() string {
	var builder strings.Builder
	builder.WriteString("Jobtitle(")
	builder.WriteString(fmt.Sprintf("id=%v", j.ID))
	builder.WriteString(", Jobtitlename=")
	builder.WriteString(j.Jobtitlename)
	builder.WriteByte(')')
	return builder.String()
}

// Jobtitles is a parsable slice of Jobtitle.
type Jobtitles []*Jobtitle

func (j Jobtitles) config(cfg config) {
	for _i := range j {
		j[_i].config = cfg
	}
}
