// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/ssaatw/app/ent/personal"
	"github.com/ssaatw/app/ent/predicate"
	"github.com/ssaatw/app/ent/systemmember"
)

// SystemmemberUpdate is the builder for updating Systemmember entities.
type SystemmemberUpdate struct {
	config
	hooks      []Hook
	mutation   *SystemmemberMutation
	predicates []predicate.Systemmember
}

// Where adds a new predicate for the builder.
func (su *SystemmemberUpdate) Where(ps ...predicate.Systemmember) *SystemmemberUpdate {
	su.predicates = append(su.predicates, ps...)
	return su
}

// SetMail sets the Mail field.
func (su *SystemmemberUpdate) SetMail(s string) *SystemmemberUpdate {
	su.mutation.SetMail(s)
	return su
}

// SetPassword sets the Password field.
func (su *SystemmemberUpdate) SetPassword(s string) *SystemmemberUpdate {
	su.mutation.SetPassword(s)
	return su
}

// AddPersonalIDs adds the personal edge to Personal by ids.
func (su *SystemmemberUpdate) AddPersonalIDs(ids ...int) *SystemmemberUpdate {
	su.mutation.AddPersonalIDs(ids...)
	return su
}

// AddPersonal adds the personal edges to Personal.
func (su *SystemmemberUpdate) AddPersonal(p ...*Personal) *SystemmemberUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return su.AddPersonalIDs(ids...)
}

// Mutation returns the SystemmemberMutation object of the builder.
func (su *SystemmemberUpdate) Mutation() *SystemmemberMutation {
	return su.mutation
}

// RemovePersonalIDs removes the personal edge to Personal by ids.
func (su *SystemmemberUpdate) RemovePersonalIDs(ids ...int) *SystemmemberUpdate {
	su.mutation.RemovePersonalIDs(ids...)
	return su
}

// RemovePersonal removes personal edges to Personal.
func (su *SystemmemberUpdate) RemovePersonal(p ...*Personal) *SystemmemberUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return su.RemovePersonalIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (su *SystemmemberUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SystemmemberMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *SystemmemberUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SystemmemberUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SystemmemberUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *SystemmemberUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   systemmember.Table,
			Columns: systemmember.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: systemmember.FieldID,
			},
		},
	}
	if ps := su.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Mail(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: systemmember.FieldMail,
		})
	}
	if value, ok := su.mutation.Password(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: systemmember.FieldPassword,
		})
	}
	if nodes := su.mutation.RemovedPersonalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   systemmember.PersonalTable,
			Columns: []string{systemmember.PersonalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: personal.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.PersonalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   systemmember.PersonalTable,
			Columns: []string{systemmember.PersonalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: personal.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemmember.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// SystemmemberUpdateOne is the builder for updating a single Systemmember entity.
type SystemmemberUpdateOne struct {
	config
	hooks    []Hook
	mutation *SystemmemberMutation
}

// SetMail sets the Mail field.
func (suo *SystemmemberUpdateOne) SetMail(s string) *SystemmemberUpdateOne {
	suo.mutation.SetMail(s)
	return suo
}

// SetPassword sets the Password field.
func (suo *SystemmemberUpdateOne) SetPassword(s string) *SystemmemberUpdateOne {
	suo.mutation.SetPassword(s)
	return suo
}

// AddPersonalIDs adds the personal edge to Personal by ids.
func (suo *SystemmemberUpdateOne) AddPersonalIDs(ids ...int) *SystemmemberUpdateOne {
	suo.mutation.AddPersonalIDs(ids...)
	return suo
}

// AddPersonal adds the personal edges to Personal.
func (suo *SystemmemberUpdateOne) AddPersonal(p ...*Personal) *SystemmemberUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return suo.AddPersonalIDs(ids...)
}

// Mutation returns the SystemmemberMutation object of the builder.
func (suo *SystemmemberUpdateOne) Mutation() *SystemmemberMutation {
	return suo.mutation
}

// RemovePersonalIDs removes the personal edge to Personal by ids.
func (suo *SystemmemberUpdateOne) RemovePersonalIDs(ids ...int) *SystemmemberUpdateOne {
	suo.mutation.RemovePersonalIDs(ids...)
	return suo
}

// RemovePersonal removes personal edges to Personal.
func (suo *SystemmemberUpdateOne) RemovePersonal(p ...*Personal) *SystemmemberUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return suo.RemovePersonalIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (suo *SystemmemberUpdateOne) Save(ctx context.Context) (*Systemmember, error) {

	var (
		err  error
		node *Systemmember
	)
	if len(suo.hooks) == 0 {
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SystemmemberMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			mut = suo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, suo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SystemmemberUpdateOne) SaveX(ctx context.Context) *Systemmember {
	s, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return s
}

// Exec executes the query on the entity.
func (suo *SystemmemberUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SystemmemberUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *SystemmemberUpdateOne) sqlSave(ctx context.Context) (s *Systemmember, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   systemmember.Table,
			Columns: systemmember.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: systemmember.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Systemmember.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := suo.mutation.Mail(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: systemmember.FieldMail,
		})
	}
	if value, ok := suo.mutation.Password(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: systemmember.FieldPassword,
		})
	}
	if nodes := suo.mutation.RemovedPersonalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   systemmember.PersonalTable,
			Columns: []string{systemmember.PersonalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: personal.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.PersonalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   systemmember.PersonalTable,
			Columns: []string{systemmember.PersonalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: personal.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	s = &Systemmember{config: suo.config}
	_spec.Assign = s.assignValues
	_spec.ScanValues = s.scanValues()
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemmember.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return s, nil
}
