// Code generated by entc, DO NOT EDIT.

package jobtitle

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/ssaatw/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Jobtitlename applies equality check predicate on the "Jobtitlename" field. It's identical to JobtitlenameEQ.
func Jobtitlename(v string) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldJobtitlename), v))
	})
}

// JobtitlenameEQ applies the EQ predicate on the "Jobtitlename" field.
func JobtitlenameEQ(v string) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldJobtitlename), v))
	})
}

// JobtitlenameNEQ applies the NEQ predicate on the "Jobtitlename" field.
func JobtitlenameNEQ(v string) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldJobtitlename), v))
	})
}

// JobtitlenameIn applies the In predicate on the "Jobtitlename" field.
func JobtitlenameIn(vs ...string) predicate.Jobtitle {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Jobtitle(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldJobtitlename), v...))
	})
}

// JobtitlenameNotIn applies the NotIn predicate on the "Jobtitlename" field.
func JobtitlenameNotIn(vs ...string) predicate.Jobtitle {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Jobtitle(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldJobtitlename), v...))
	})
}

// JobtitlenameGT applies the GT predicate on the "Jobtitlename" field.
func JobtitlenameGT(v string) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldJobtitlename), v))
	})
}

// JobtitlenameGTE applies the GTE predicate on the "Jobtitlename" field.
func JobtitlenameGTE(v string) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldJobtitlename), v))
	})
}

// JobtitlenameLT applies the LT predicate on the "Jobtitlename" field.
func JobtitlenameLT(v string) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldJobtitlename), v))
	})
}

// JobtitlenameLTE applies the LTE predicate on the "Jobtitlename" field.
func JobtitlenameLTE(v string) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldJobtitlename), v))
	})
}

// JobtitlenameContains applies the Contains predicate on the "Jobtitlename" field.
func JobtitlenameContains(v string) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldJobtitlename), v))
	})
}

// JobtitlenameHasPrefix applies the HasPrefix predicate on the "Jobtitlename" field.
func JobtitlenameHasPrefix(v string) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldJobtitlename), v))
	})
}

// JobtitlenameHasSuffix applies the HasSuffix predicate on the "Jobtitlename" field.
func JobtitlenameHasSuffix(v string) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldJobtitlename), v))
	})
}

// JobtitlenameEqualFold applies the EqualFold predicate on the "Jobtitlename" field.
func JobtitlenameEqualFold(v string) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldJobtitlename), v))
	})
}

// JobtitlenameContainsFold applies the ContainsFold predicate on the "Jobtitlename" field.
func JobtitlenameContainsFold(v string) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldJobtitlename), v))
	})
}

// HasPersonal applies the HasEdge predicate on the "personal" edge.
func HasPersonal() predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PersonalTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PersonalTable, PersonalColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPersonalWith applies the HasEdge predicate on the "personal" edge with a given conditions (other predicates).
func HasPersonalWith(preds ...predicate.Personal) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PersonalInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PersonalTable, PersonalColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Jobtitle) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Jobtitle) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Jobtitle) predicate.Jobtitle {
	return predicate.Jobtitle(func(s *sql.Selector) {
		p(s.Not())
	})
}
