// Code generated by entc, DO NOT EDIT.

package personal

import (
	"time"
)

const (
	// Label holds the string label denoting the personal type in the database.
	Label = "personal"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPersonalName holds the string denoting the personalname field in the database.
	FieldPersonalName = "personal_name"
	// FieldPersonalMail holds the string denoting the personalmail field in the database.
	FieldPersonalMail = "personal_mail"
	// FieldPersonalPhone holds the string denoting the personalphone field in the database.
	FieldPersonalPhone = "personal_phone"
	// FieldPersonalDob holds the string denoting the personaldob field in the database.
	FieldPersonalDob = "personal_dob"
	// FieldAdded holds the string denoting the added field in the database.
	FieldAdded = "added"

	// EdgeJobtitle holds the string denoting the jobtitle edge name in mutations.
	EdgeJobtitle = "jobtitle"
	// EdgeDepartment holds the string denoting the department edge name in mutations.
	EdgeDepartment = "department"
	// EdgeSystemmember holds the string denoting the systemmember edge name in mutations.
	EdgeSystemmember = "systemmember"

	// Table holds the table name of the personal in the database.
	Table = "personals"
	// JobtitleTable is the table the holds the jobtitle relation/edge.
	JobtitleTable = "personals"
	// JobtitleInverseTable is the table name for the Jobtitle entity.
	// It exists in this package in order to avoid circular dependency with the "jobtitle" package.
	JobtitleInverseTable = "jobtitles"
	// JobtitleColumn is the table column denoting the jobtitle relation/edge.
	JobtitleColumn = "jobtitle_id"
	// DepartmentTable is the table the holds the department relation/edge.
	DepartmentTable = "personals"
	// DepartmentInverseTable is the table name for the Department entity.
	// It exists in this package in order to avoid circular dependency with the "department" package.
	DepartmentInverseTable = "departments"
	// DepartmentColumn is the table column denoting the department relation/edge.
	DepartmentColumn = "department_id"
	// SystemmemberTable is the table the holds the systemmember relation/edge.
	SystemmemberTable = "personals"
	// SystemmemberInverseTable is the table name for the Systemmember entity.
	// It exists in this package in order to avoid circular dependency with the "systemmember" package.
	SystemmemberInverseTable = "systemmembers"
	// SystemmemberColumn is the table column denoting the systemmember relation/edge.
	SystemmemberColumn = "systemmember_id"
)

// Columns holds all SQL columns for personal fields.
var Columns = []string{
	FieldID,
	FieldPersonalName,
	FieldPersonalMail,
	FieldPersonalPhone,
	FieldPersonalDob,
	FieldAdded,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Personal type.
var ForeignKeys = []string{
	"department_id",
	"jobtitle_id",
	"systemmember_id",
}

var (
	// DefaultAdded holds the default value on creation for the Added field.
	DefaultAdded func() time.Time
)
