// Code generated by entc, DO NOT EDIT.

package personal

import (
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/ssaatw/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// PersonalName applies equality check predicate on the "PersonalName" field. It's identical to PersonalNameEQ.
func PersonalName(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPersonalName), v))
	})
}

// PersonalMail applies equality check predicate on the "PersonalMail" field. It's identical to PersonalMailEQ.
func PersonalMail(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPersonalMail), v))
	})
}

// PersonalPhone applies equality check predicate on the "PersonalPhone" field. It's identical to PersonalPhoneEQ.
func PersonalPhone(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPersonalPhone), v))
	})
}

// Added applies equality check predicate on the "Added" field. It's identical to AddedEQ.
func Added(v time.Time) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAdded), v))
	})
}

// PersonalNameEQ applies the EQ predicate on the "PersonalName" field.
func PersonalNameEQ(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPersonalName), v))
	})
}

// PersonalNameNEQ applies the NEQ predicate on the "PersonalName" field.
func PersonalNameNEQ(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPersonalName), v))
	})
}

// PersonalNameIn applies the In predicate on the "PersonalName" field.
func PersonalNameIn(vs ...string) predicate.Personal {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Personal(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPersonalName), v...))
	})
}

// PersonalNameNotIn applies the NotIn predicate on the "PersonalName" field.
func PersonalNameNotIn(vs ...string) predicate.Personal {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Personal(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPersonalName), v...))
	})
}

// PersonalNameGT applies the GT predicate on the "PersonalName" field.
func PersonalNameGT(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPersonalName), v))
	})
}

// PersonalNameGTE applies the GTE predicate on the "PersonalName" field.
func PersonalNameGTE(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPersonalName), v))
	})
}

// PersonalNameLT applies the LT predicate on the "PersonalName" field.
func PersonalNameLT(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPersonalName), v))
	})
}

// PersonalNameLTE applies the LTE predicate on the "PersonalName" field.
func PersonalNameLTE(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPersonalName), v))
	})
}

// PersonalNameContains applies the Contains predicate on the "PersonalName" field.
func PersonalNameContains(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldPersonalName), v))
	})
}

// PersonalNameHasPrefix applies the HasPrefix predicate on the "PersonalName" field.
func PersonalNameHasPrefix(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldPersonalName), v))
	})
}

// PersonalNameHasSuffix applies the HasSuffix predicate on the "PersonalName" field.
func PersonalNameHasSuffix(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldPersonalName), v))
	})
}

// PersonalNameEqualFold applies the EqualFold predicate on the "PersonalName" field.
func PersonalNameEqualFold(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldPersonalName), v))
	})
}

// PersonalNameContainsFold applies the ContainsFold predicate on the "PersonalName" field.
func PersonalNameContainsFold(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldPersonalName), v))
	})
}

// PersonalMailEQ applies the EQ predicate on the "PersonalMail" field.
func PersonalMailEQ(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPersonalMail), v))
	})
}

// PersonalMailNEQ applies the NEQ predicate on the "PersonalMail" field.
func PersonalMailNEQ(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPersonalMail), v))
	})
}

// PersonalMailIn applies the In predicate on the "PersonalMail" field.
func PersonalMailIn(vs ...string) predicate.Personal {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Personal(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPersonalMail), v...))
	})
}

// PersonalMailNotIn applies the NotIn predicate on the "PersonalMail" field.
func PersonalMailNotIn(vs ...string) predicate.Personal {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Personal(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPersonalMail), v...))
	})
}

// PersonalMailGT applies the GT predicate on the "PersonalMail" field.
func PersonalMailGT(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPersonalMail), v))
	})
}

// PersonalMailGTE applies the GTE predicate on the "PersonalMail" field.
func PersonalMailGTE(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPersonalMail), v))
	})
}

// PersonalMailLT applies the LT predicate on the "PersonalMail" field.
func PersonalMailLT(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPersonalMail), v))
	})
}

// PersonalMailLTE applies the LTE predicate on the "PersonalMail" field.
func PersonalMailLTE(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPersonalMail), v))
	})
}

// PersonalMailContains applies the Contains predicate on the "PersonalMail" field.
func PersonalMailContains(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldPersonalMail), v))
	})
}

// PersonalMailHasPrefix applies the HasPrefix predicate on the "PersonalMail" field.
func PersonalMailHasPrefix(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldPersonalMail), v))
	})
}

// PersonalMailHasSuffix applies the HasSuffix predicate on the "PersonalMail" field.
func PersonalMailHasSuffix(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldPersonalMail), v))
	})
}

// PersonalMailEqualFold applies the EqualFold predicate on the "PersonalMail" field.
func PersonalMailEqualFold(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldPersonalMail), v))
	})
}

// PersonalMailContainsFold applies the ContainsFold predicate on the "PersonalMail" field.
func PersonalMailContainsFold(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldPersonalMail), v))
	})
}

// PersonalPhoneEQ applies the EQ predicate on the "PersonalPhone" field.
func PersonalPhoneEQ(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPersonalPhone), v))
	})
}

// PersonalPhoneNEQ applies the NEQ predicate on the "PersonalPhone" field.
func PersonalPhoneNEQ(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPersonalPhone), v))
	})
}

// PersonalPhoneIn applies the In predicate on the "PersonalPhone" field.
func PersonalPhoneIn(vs ...string) predicate.Personal {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Personal(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPersonalPhone), v...))
	})
}

// PersonalPhoneNotIn applies the NotIn predicate on the "PersonalPhone" field.
func PersonalPhoneNotIn(vs ...string) predicate.Personal {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Personal(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPersonalPhone), v...))
	})
}

// PersonalPhoneGT applies the GT predicate on the "PersonalPhone" field.
func PersonalPhoneGT(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPersonalPhone), v))
	})
}

// PersonalPhoneGTE applies the GTE predicate on the "PersonalPhone" field.
func PersonalPhoneGTE(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPersonalPhone), v))
	})
}

// PersonalPhoneLT applies the LT predicate on the "PersonalPhone" field.
func PersonalPhoneLT(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPersonalPhone), v))
	})
}

// PersonalPhoneLTE applies the LTE predicate on the "PersonalPhone" field.
func PersonalPhoneLTE(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPersonalPhone), v))
	})
}

// PersonalPhoneContains applies the Contains predicate on the "PersonalPhone" field.
func PersonalPhoneContains(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldPersonalPhone), v))
	})
}

// PersonalPhoneHasPrefix applies the HasPrefix predicate on the "PersonalPhone" field.
func PersonalPhoneHasPrefix(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldPersonalPhone), v))
	})
}

// PersonalPhoneHasSuffix applies the HasSuffix predicate on the "PersonalPhone" field.
func PersonalPhoneHasSuffix(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldPersonalPhone), v))
	})
}

// PersonalPhoneEqualFold applies the EqualFold predicate on the "PersonalPhone" field.
func PersonalPhoneEqualFold(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldPersonalPhone), v))
	})
}

// PersonalPhoneContainsFold applies the ContainsFold predicate on the "PersonalPhone" field.
func PersonalPhoneContainsFold(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldPersonalPhone), v))
	})
}

// AddedEQ applies the EQ predicate on the "Added" field.
func AddedEQ(v time.Time) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAdded), v))
	})
}

// AddedNEQ applies the NEQ predicate on the "Added" field.
func AddedNEQ(v time.Time) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldAdded), v))
	})
}

// AddedIn applies the In predicate on the "Added" field.
func AddedIn(vs ...time.Time) predicate.Personal {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Personal(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldAdded), v...))
	})
}

// AddedNotIn applies the NotIn predicate on the "Added" field.
func AddedNotIn(vs ...time.Time) predicate.Personal {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Personal(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldAdded), v...))
	})
}

// AddedGT applies the GT predicate on the "Added" field.
func AddedGT(v time.Time) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldAdded), v))
	})
}

// AddedGTE applies the GTE predicate on the "Added" field.
func AddedGTE(v time.Time) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldAdded), v))
	})
}

// AddedLT applies the LT predicate on the "Added" field.
func AddedLT(v time.Time) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldAdded), v))
	})
}

// AddedLTE applies the LTE predicate on the "Added" field.
func AddedLTE(v time.Time) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldAdded), v))
	})
}

// HasJobtitle applies the HasEdge predicate on the "jobtitle" edge.
func HasJobtitle() predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(JobtitleTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, JobtitleTable, JobtitleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasJobtitleWith applies the HasEdge predicate on the "jobtitle" edge with a given conditions (other predicates).
func HasJobtitleWith(preds ...predicate.Jobtitle) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(JobtitleInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, JobtitleTable, JobtitleColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDepartment applies the HasEdge predicate on the "department" edge.
func HasDepartment() predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DepartmentTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DepartmentTable, DepartmentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDepartmentWith applies the HasEdge predicate on the "department" edge with a given conditions (other predicates).
func HasDepartmentWith(preds ...predicate.Department) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DepartmentInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DepartmentTable, DepartmentColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSystemmember applies the HasEdge predicate on the "systemmember" edge.
func HasSystemmember() predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SystemmemberTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SystemmemberTable, SystemmemberColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSystemmemberWith applies the HasEdge predicate on the "systemmember" edge with a given conditions (other predicates).
func HasSystemmemberWith(preds ...predicate.Systemmember) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SystemmemberInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SystemmemberTable, SystemmemberColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Personal) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Personal) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Personal) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		p(s.Not())
	})
}
