// Code generated by entc, DO NOT EDIT.

package personal

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/ssaatw/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// PersonalName applies equality check predicate on the "PersonalName" field. It's identical to PersonalNameEQ.
func PersonalName(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPersonalName), v))
	})
}

// PersonalNameEQ applies the EQ predicate on the "PersonalName" field.
func PersonalNameEQ(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPersonalName), v))
	})
}

// PersonalNameNEQ applies the NEQ predicate on the "PersonalName" field.
func PersonalNameNEQ(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPersonalName), v))
	})
}

// PersonalNameIn applies the In predicate on the "PersonalName" field.
func PersonalNameIn(vs ...string) predicate.Personal {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Personal(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPersonalName), v...))
	})
}

// PersonalNameNotIn applies the NotIn predicate on the "PersonalName" field.
func PersonalNameNotIn(vs ...string) predicate.Personal {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Personal(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPersonalName), v...))
	})
}

// PersonalNameGT applies the GT predicate on the "PersonalName" field.
func PersonalNameGT(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPersonalName), v))
	})
}

// PersonalNameGTE applies the GTE predicate on the "PersonalName" field.
func PersonalNameGTE(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPersonalName), v))
	})
}

// PersonalNameLT applies the LT predicate on the "PersonalName" field.
func PersonalNameLT(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPersonalName), v))
	})
}

// PersonalNameLTE applies the LTE predicate on the "PersonalName" field.
func PersonalNameLTE(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPersonalName), v))
	})
}

// PersonalNameContains applies the Contains predicate on the "PersonalName" field.
func PersonalNameContains(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldPersonalName), v))
	})
}

// PersonalNameHasPrefix applies the HasPrefix predicate on the "PersonalName" field.
func PersonalNameHasPrefix(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldPersonalName), v))
	})
}

// PersonalNameHasSuffix applies the HasSuffix predicate on the "PersonalName" field.
func PersonalNameHasSuffix(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldPersonalName), v))
	})
}

// PersonalNameEqualFold applies the EqualFold predicate on the "PersonalName" field.
func PersonalNameEqualFold(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldPersonalName), v))
	})
}

// PersonalNameContainsFold applies the ContainsFold predicate on the "PersonalName" field.
func PersonalNameContainsFold(v string) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldPersonalName), v))
	})
}

// HasJobtitle applies the HasEdge predicate on the "jobtitle" edge.
func HasJobtitle() predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(JobtitleTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, JobtitleTable, JobtitleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasJobtitleWith applies the HasEdge predicate on the "jobtitle" edge with a given conditions (other predicates).
func HasJobtitleWith(preds ...predicate.Jobtitle) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(JobtitleInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, JobtitleTable, JobtitleColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDepartment applies the HasEdge predicate on the "department" edge.
func HasDepartment() predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DepartmentTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DepartmentTable, DepartmentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDepartmentWith applies the HasEdge predicate on the "department" edge with a given conditions (other predicates).
func HasDepartmentWith(preds ...predicate.Department) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DepartmentInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DepartmentTable, DepartmentColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGender applies the HasEdge predicate on the "gender" edge.
func HasGender() predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(GenderTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GenderTable, GenderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGenderWith applies the HasEdge predicate on the "gender" edge with a given conditions (other predicates).
func HasGenderWith(preds ...predicate.Gender) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(GenderInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GenderTable, GenderColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Personal) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Personal) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Personal) predicate.Personal {
	return predicate.Personal(func(s *sql.Selector) {
		p(s.Not())
	})
}
