// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// DepartmentsColumns holds the columns for the "departments" table.
	DepartmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "departmentname", Type: field.TypeString, Unique: true},
	}
	// DepartmentsTable holds the schema information for the "departments" table.
	DepartmentsTable = &schema.Table{
		Name:        "departments",
		Columns:     DepartmentsColumns,
		PrimaryKey:  []*schema.Column{DepartmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// GendersColumns holds the columns for the "genders" table.
	GendersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "gendername", Type: field.TypeString, Unique: true},
	}
	// GendersTable holds the schema information for the "genders" table.
	GendersTable = &schema.Table{
		Name:        "genders",
		Columns:     GendersColumns,
		PrimaryKey:  []*schema.Column{GendersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// JobtitlesColumns holds the columns for the "jobtitles" table.
	JobtitlesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "jobtitlename", Type: field.TypeString, Unique: true},
	}
	// JobtitlesTable holds the schema information for the "jobtitles" table.
	JobtitlesTable = &schema.Table{
		Name:        "jobtitles",
		Columns:     JobtitlesColumns,
		PrimaryKey:  []*schema.Column{JobtitlesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// PersonalsColumns holds the columns for the "personals" table.
	PersonalsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "personal_name", Type: field.TypeString},
		{Name: "department_id", Type: field.TypeInt, Nullable: true},
		{Name: "gender_id", Type: field.TypeInt, Nullable: true},
		{Name: "jobtitle_id", Type: field.TypeInt, Nullable: true},
	}
	// PersonalsTable holds the schema information for the "personals" table.
	PersonalsTable = &schema.Table{
		Name:       "personals",
		Columns:    PersonalsColumns,
		PrimaryKey: []*schema.Column{PersonalsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "personals_departments_personal",
				Columns: []*schema.Column{PersonalsColumns[2]},

				RefColumns: []*schema.Column{DepartmentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "personals_genders_personal",
				Columns: []*schema.Column{PersonalsColumns[3]},

				RefColumns: []*schema.Column{GendersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "personals_jobtitles_personal",
				Columns: []*schema.Column{PersonalsColumns[4]},

				RefColumns: []*schema.Column{JobtitlesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DepartmentsTable,
		GendersTable,
		JobtitlesTable,
		PersonalsTable,
	}
)

func init() {
	PersonalsTable.ForeignKeys[0].RefTable = DepartmentsTable
	PersonalsTable.ForeignKeys[1].RefTable = GendersTable
	PersonalsTable.ForeignKeys[2].RefTable = JobtitlesTable
}
