/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersPersonal
 */
export interface ControllersPersonal {
    /**
     * 
     * @type {string}
     * @memberof ControllersPersonal
     */
    added?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersPersonal
     */
    department?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPersonal
     */
    jobtitle?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersPersonal
     */
    personalMail?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersPersonal
     */
    personalName?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersPersonal
     */
    personalPhone?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersPersonal
     */
    personaldata?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPersonal
     */
    systemmember?: number;
}

export function ControllersPersonalFromJSON(json: any): ControllersPersonal {
    return ControllersPersonalFromJSONTyped(json, false);
}

export function ControllersPersonalFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersPersonal {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'added': !exists(json, 'added') ? undefined : json['added'],
        'department': !exists(json, 'department') ? undefined : json['department'],
        'jobtitle': !exists(json, 'jobtitle') ? undefined : json['jobtitle'],
        'personalMail': !exists(json, 'personalMail') ? undefined : json['personalMail'],
        'personalName': !exists(json, 'personalName') ? undefined : json['personalName'],
        'personalPhone': !exists(json, 'personalPhone') ? undefined : json['personalPhone'],
        'personaldata': !exists(json, 'personaldata') ? undefined : json['personaldata'],
        'systemmember': !exists(json, 'systemmember') ? undefined : json['systemmember'],
    };
}

export function ControllersPersonalToJSON(value?: ControllersPersonal | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'added': value.added,
        'department': value.department,
        'jobtitle': value.jobtitle,
        'personalMail': value.personalMail,
        'personalName': value.personalName,
        'personalPhone': value.personalPhone,
        'personaldata': value.personaldata,
        'systemmember': value.systemmember,
    };
}


