/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersPersonal
 */
export interface ControllersPersonal {
    /**
     * 
     * @type {number}
     * @memberof ControllersPersonal
     */
    department?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPersonal
     */
    gender?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPersonal
     */
    jobtitle?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersPersonal
     */
    personalName?: string;
}

export function ControllersPersonalFromJSON(json: any): ControllersPersonal {
    return ControllersPersonalFromJSONTyped(json, false);
}

export function ControllersPersonalFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersPersonal {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'department': !exists(json, 'department') ? undefined : json['department'],
        'gender': !exists(json, 'gender') ? undefined : json['gender'],
        'jobtitle': !exists(json, 'jobtitle') ? undefined : json['jobtitle'],
        'personalName': !exists(json, 'personalName') ? undefined : json['personalName'],
    };
}

export function ControllersPersonalToJSON(value?: ControllersPersonal | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'department': value.department,
        'gender': value.gender,
        'jobtitle': value.jobtitle,
        'personalName': value.personalName,
    };
}


